services:
  moncraft-rofl:
    platform: linux/amd64
    image: docker.io/dockede/moncraft
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    environment:
      - PORT=5100
      - RPC_URL=${RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - NFT_CONTRACT_ADDRESS=${NFT_CONTRACT_ADDRESS}
      - ROFL_ACCESS_CODE=${ROFL_ACCESS_CODE}
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock
